/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UAlert: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UAvatar: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UEditor: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Editor.vue')['default']
    UEditorDragHandle: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue')['default']
    UEditorEmojiMenu: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/EditorEmojiMenu.vue')['default']
    UEditorSuggestionMenu: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue')['default']
    UEditorToolbar: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue')['default']
    UForm: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPagination: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    USelect: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USkeleton: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USwitch: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTextarea: typeof import('./D:/Data web/VD/APIco/apico/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
